---
# tasks file for flatpaks

- name: Add Flatpak remote for Flathub
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    method: user
    flatpakrepo_url: "{{ item.url }}"
  loop: "{{ flatpak_remote_install }}"

- name: Update metadata to show newly-available software
  ansible.builtin.command: flatpak update --appstream

- name: Install Flatpak packages
  community.general.flatpak:
    name: "{{ item.package }}"
    state: present
    method: user
    remote: "{{ item.remote }}"
  loop: "{{ flatpak_package_install }}"
